theme: jekyll-theme-minimal
title: "CV"
#description: University of Chicago \| FMNH
author: Jonathan A. Nations
jobtitle: "NSF Postdoctoral Research Fellow"
address: "Department of the Geophysical Sciences"
jobtitle2: "University of Chicago "