---
#output: stevetemplates::cv
output: 
  pdf_document:
    latex_engine: pdflatex
    template: svm-latex-cv.tex
geometry: margin=0.825in

title: "CV"
author: Jonathan A. Nations
jobtitle: "NSF Postdoctoral Research Fellow"
address: "Department of the Geophysical Sciences"
jobtitle2: "University of Chicago "
#address2: "Guinness Brewery · Park Royal · London NW10 7RR, UK"
fontawesome: yes
email: jonnations@gmail.com
github: jonnations
# twitter: stevenvmiller
#osf: "Enter 5 digit osf string here"
#phone: "+353 1 408 4800"
web: jonnynations.com
updated: TRUE
rdateformat: "`r format(Sys.time(), '%d %b %Y')`"

keywords: R Markdown, academic CV, template

#fontawesome: yes
fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 10pt
linkcolor: black
urlcolor: black
---
## Education  
\everypar{\hangindent=2.2cm \hangafter=1}
  
  
**2015 - 2020** \| **PhD**, Biological Sciences, Louisiana State University\
Dissertation: [Function, history, and ecology in the exceptional diversification]{.smallcaps}\
[of murine rodents]{.smallcaps}

**2011 - 2014** \| **BSc**, Biological Sciences, University of Alaska Fairbanks\
Undergraduate Thesis: [Climbing behavior of northern Red-backed voles and]{.smallcaps}\
[scansoriality in *Myodes*]{.smallcaps}

**2008 - 2011** \| **ASc**, Science and Math, Seattle Central Community College  
<!--
Spacing-->

## Recent Professional Experience 
\everypar{\hangindent=2.5cm \hangafter=1}

\textbf{2020\enskip-\enskip2023}\enskip\|\enskip\textbf{NSF Postdoctoral Research Fellowship in Biology}:  
Interdisciplinary Research Using Biological Collections

\textbf{2020\enskip-\enskip2025}\enskip\|\enskip\textbf{Research Affiliate}: Field Museum of Natural History

\textbf{2015\enskip-\enskip2018}\enskip\|\enskip\textbf{Curatorial Assistantship}: Mammals Division, LSU Museum of Natural Science   

\textbf{2014\enskip-\enskip2015}\enskip\|\enskip\textbf{Assistant Collections Manager}: Mammals Division, University of Alaska Museum  

\textbf{2014\enskip-\enskip2015}\enskip\|\enskip\textbf{Intern, Student Conservation Association}: Denali National Park &  
University of Alaska Museum  

\textbf{2011\enskip-\enskip2014}\enskip\|\enskip\textbf{Curatorial Assistant}: Mammals Division, University of Alaska Museum\
<!--
Spacing-->

## Grants, Scholarships, and Awards  
\everypar{\hangindent=1.33cm \hangafter=1}

\textbf{2022}\enskip\|\enskip\textbf{Grainger Bioinformatics Center, Field Museum} *(\$5,700)*  
Project: Dietary metabarcoding of Sulawesi shrews  

\textbf{2020}\enskip\|\enskip\textbf{American Society of Mammalogists Fellowship} *(\$20,000)*  
The highest award made to a graduate student member of ASM

\textbf{2020}\enskip\|\enskip\textbf{LSU Museum of Natural Science Outstanding Graduate Student}  
Awarded to a graduate student who has made substantial contributions to science and the museum community

\textbf{2019}\enskip\|\enskip\textbf{Louisiana State University Prestigious Graduate Fellowship Award} *(\$4,000)*  
Awarded to select students for funding dissertation research

\textbf{2019}\enskip\|\enskip\textbf{Research Triangle Nanotechnology Network Award} *(\$2,000)*  
Support for $\mu$CT scanning museum specimens at Duke University

\textbf{2018}\enskip\|\enskip\textbf{American Society of Mammalogists Patton Award} *(\$5,000)*  
Support for museum-based research by graduate student members of ASM

\textbf{2017}\enskip\|\enskip\textbf{NSF East Asia Pacific Studies Institute Fellow} *(\$8,000)*  
Sponsor: Dr. Kevin Rowe, Museums Victoria, Melbourne, Australia  

\textbf{2016}\enskip\|\enskip\textbf{Society of Systematic Biologists Graduate Student Research Award} *(\$1,200)*  

\textbf{2016}\enskip\|\enskip\textbf{American Society of Mammalogists Grant in Aid} *(\$1,000)*  
Awarded to select ASM members for funding dissertation research  

\textbf{2015}\enskip\|\enskip\textbf{National Science Foundation Graduate Research Fellowship} *(\$138,000)*  
Three years of support over a five-year fellowship period for individuals who have demonstrated their potential for significant research achievements in STEM 

\textbf{2014}\enskip\|\enskip\textbf{Outstanding Undergraduate Student: Biological Sciences, University of Alaska Fairbanks}  
Awarded annually to one student in each division of the College of Natural Sciences and Mathematics

\textbf{2014}\enskip\|\enskip\textbf{Brina Kessel Medal for Excellence in Science, University of Alaska Fairbanks} *(\$500)*  
Awarded annually to one student that demonstrated a commitment to their chosen scientific field, has an inquiring mind, has participated in true research activities of some kind, and demonstrates high levels of integrity in all matters  

\textbf{2013}\enskip\|\enskip\textbf{Summer Undergraduate Research Award, University of Alaska Fairbanks} *(\$5000)*  

\textbf{2013}\enskip\|\enskip\textbf{American Society of Mammalogists Travel Award} *(\$300)*  

\textbf{2012}\enskip\|\enskip\textbf{Summer Undergraduate Research Award, University of Alaska Fairbanks} *(\$5000)*\


<!--
UAF Research Day: 2013 Winner, First Place, Best Oral Presentation ($1,000)
UAF Undergraduate Travel Award: 2011 ($1,995)
To attend conference in Philadelphia, PA
Fred Beeler Memorial Scholarship: 2012-2013 ($3,000)
Distributed by UAF to outstanding undergraduate students
-->  

## Publications  
\everypar{\hangindent=1.26cm \hangafter=1}

**2022** \| **JA Nations**, H Handika, A Mursyid, R Darma Busta, Apandi, AS Achmadi, JA Esselstyn. Three new species of shrew (Soricidae: *Crocidura*) from West Sumatra, Indonesia: elevational and morphological divergence in syntopic, sister taxa. *In Revision*

**2022** \| **JA Nations**, TC Giarla, A Morni, J William-Dee, MT Swanson, AE Hiller, F Khan, JA Esselstyn. Molecular data from the holotype of the enigmatic Bornean Black Shrew, *Suncus ater*, place it in the genus *Palawanosorex*. ZooKeys. 1137:17-31. [ZooKeys hyperlink](https://zookeys.pensoft.net/article/94217/)

**2022** \| **JA Nations**, BA Kohli, H Handika, AS Achmadi, MJ Polito, KC Rowe, JA Esselstyn. Trait-specific patterns of community ecospace occupancy in an insular mammal radiation. *In Revision*. [bioRxiv hyperlink](https://www.biorxiv.org/content/10.1101/2022.07.15.500274v1)

**2022** \| Wisniewski, AL\*, **JA Nations**\*, & GJ Slater. Bayesian prediction of multivariate ecology from phenotypic data yields novel insights into the diets of extant and extinct taxa. *In Revision*. [bioRxiv hyperlink](https://www.biorxiv.org/content/10.1101/2022.05.05.490807v1)\
\**Joint first authorship*

**2022** \| Swanson, MT, AS Achmadi, **JA Nations**, MW Henson, H Handika, S Anita, KC Rowe, H Bennadji, MJ Polito & JA Esselstyn. Bacterial families variably associated with diet along the gut in a trophically diverse community of wild rodents. *In Review*

**2021** \| Marcondes, RS\*, **JA Nations**\*, GF Seeholzer, & RT Brumfield. 2021. Rethinking Gloger's rule: climate, light environments, and color in a diverse family of tropical birds. The American Naturalist. 197(5): 592-606.\
\**Joint first authorship*

**2021** \| **Nations, JA**, GG Mount, SM Morere\*, AS Achmadi, KC Rowe, & JA Esselstyn. Locomotory mode transitions alter phenotypic evolution and lineage diversification in an ecologically rich clade of mammals. Evolution. 75(2): 376-393.\
\**Undergraduate author*

**2021** \| **Nations, JA**, A Mursyid\*, R Darma Busta\*, SP Adrian\*, H Handika, Apandi, AS Achmadi, & JA Esselstyn. An albino rat from West Sumatra, Indonesia represents the first report of albinism in a Sundaland rodent. Mammalia. 85(2): 168-172.\
\**Undergraduate author*

**2020** \| Roycroft, EJ\*, **JA Nations**\*, & KC Rowe. Environment predicts repeated body size shifts in a recent radiation of Australian mammals. Evolution. 74(3): 671-680.\
\**Joint first authorship*

**2019** \| **Nations, JA**, LR Heaney, TC Demos, AS Achmadi, KC Rowe, & JA Esselstyn. A Simple Skeletal Measurement Effectively Predicts Climbing Behavior in Murine Rodents. Biological Journal of the Linnean Society. 128(2): 323-336.\
*Selected for BJLS Ecomorphology Collection Virtual Issue*

**2015** \| **Nations, JA** & LE Olson. Climbing behavior of northern red-backed voles (Myodes rutilus) and scansoriality in Myodes (Rodentia, Cricetidae). Journal of Mammalogy 96(5): 957--963.\
<!--
-->
\bigskip\bigskip

## Invited & Departmental Seminars
\everypar{\hangindent=1.23cm \hangafter=1}

**2022** \| Departmental Seminar, Canadian Natural History Museum, Ottowa, ON  
*Modern take on the classics: Using probabilistic methods to investigate ecogeographical theories in understudied vertebrate groups*  

**2021** \| EvMorph Seminar, University of Chicago, Chicago, IL  
*Function, history, and ecology in two exceptional (and exceptionally different) mammal radiations*  

**2021** \| Departmental Seminar, Sienna College, Loudonville, NY  
*Function, history, and ecology in the exceptional diversification of murine rodents*  

**2019** \| LSU Museum of Natural Science Seminar, Baton Rouge, LA  
*Travelogue: Gunung Murud Expedition, Sarawak, Malaysia, July – August 2019*  

**2019** \| LSU Museum of Natural Science Seminar, Baton Rouge, LA  
*Travelogue: The Giant Rat of Sumatra: Gunung Singgalang Expedition, West Sumatra, Indonesia*  

**2018** \| Biology Seminar, Andalas University, Padang, West Sumatra, Indonesia  
*The importance of museum specimens in the study of natural history*  

**2017** \| LSU Museum of Natural Science Seminar, Baton Rouge, LA  
*Travelogue: "Field Work in Borneo: Mt. Mulu, Sarawak, Malaysia*  

**2015** \| LSU Museum of Natural Science Seminar, Baton Rouge, LA  
*Travelogue: "Small Mammals in Ouachita National Forest, Arkansas*  \


## Conference Presentations
\everypar{\hangindent=1.23cm \hangafter=1}

**2022** \| American Society of Mammalogists Annual Meeting, Tucson, AZ  
*Bayesian prediction of multivariate ecology from phenotypic data yields novel insights into the diets of extant and extinct taxa*

**2021** \| American Society of Mammalogists Annual Meeting - Plenary Session, Virtual Meeting  
*Niche packing, niche expansion, and the evolution of the exceptional rodent fauna of Sulawesi, Indonesia*  

**2019** \| American Society of Mammalogists Annual Meeting, Washington D.C.  
*Bergmann’s Rule in a recent radiation of Australian mammals*   

**2019** \| Evolution, Providence, RI  
*Environment predicts repeated body size shifts in a recent radiation of Australian mammals*  

**2019** \| LSU BioGrads Symposium, Baton Rouge, LA  \**poster*  
*The locomotion and biogeography of Indo-Australian Archipelago rodents*  
*Winner - Best Poster*  

**2018** \| Evolution, Montpellier, France  \**poster*  
*The biogeography of murine locomotion across the Indo-Australian Archipelago*  

**2018** \| American Society of Mammalogists Annual Meeting, Manhattan, KS  
*The role of locomotor mode in lineage turnover and persistence among Indo-Australian rats and mice*   

**2017** \| 12th International Mammalogical Congress, Perth, Australia  
*The role of in-situ speciation in the generation of biodiversity across the Indo-Australian Archipelago*   

**2016** \| American Society of Mammalogists Annual Meeting, Minneapolis, MN  
*How do voles adapt? Ecomorphology of small-bodied North American rodents*  

**2016** \| Evolution, Austin, TX  
*Ecomorphological variation in the limbs of small-bodied “generalists:” a test case with voles*  

**2014** \| American Society of Mammalogists Annual Meeting, Oklahoma City, OK  
*Is climbing behavior reflected in the morphology of scansorial voles?*  

**2013** \| American Society of Mammalogists Annual Meeting, Philadelphia, PA  
*Climbing in the Northern Red-backed Vole (Myodes rutilus)*  

**2013** \| UAF Undergraduate Research Day, Fairbanks, AK  
*Climbing in the Northern Red-backed Vole (Myodes rutilus)*  
*Winner: Best Oral Presentation*

**2011** \| American Society of Mammalogists Annual Meeting, Portland, OR  \**poster*  
*The effects of habitat size on small mammal diversity in Seattle City Parks*  

**2010** \| Mary Gates Undergrad Research Symposium; University of Washington \**poster*  
*Small mammal diversity in Seattle City Parks*  \

## Mentorship
\everypar{\hangindent=1.23cm \hangafter=1}

**Undergraduates** \|  **Shelby Oliveaux** (*2019-20 - LSU - Collecting and processing geometric morphometric data*), \ **Collin Cooper**
(*2019-20 - LSU - Processing microCT scan data for 3D morphometrics*), **Finaz Wan Azman**, **Syam Zuraini** (*2019 - University of Malaysia, Sarawak - Collection and preparation of museum specimens and associated tissue samples*) **Ahmad Mursyid**, **Ryski Darma Busta**, **Taufiq Afdhal**, **Andri Saputra**, **Tengku Lidra**, **Sah Putra Adrian** (*2018 - Andalas University, Padang, Indonesia - Collection and preparation of museum specimens and associated tissue samples*), **Derra Leonard** (*2016-2019 -  Curatorial Assistant*), **Sara Morere** (*2016 -  Research on locomotor modes of murine rodents (manuscript co-author)*),	**Rajvi Jariwala**, **Shay Cook** (*2015-2016 - LSU - Curatorial methods and molecular lab work*), **Chris Reglan** (*2015-2016 - LSU - Curatorial methods*), **Sarah Swanson** (*2014-2015 - University of Alaska Museum - Identification, preparation and curation of museum specimens from Denali National Park*)

**High School Students** \|  **Stefania Kremer**, **Briana Kremer** (*2014-2015 - University of Alaska Museum - Identification, preparation and curation of museum specimens from Denali National Park*), **Kelly May** (*2012-2015 - University of Alaska Museum - Research on the effects of climate change on the body size of Alaska's shrews*)\


## Teaching & Training
\everypar{\hangindent=1.23cm \hangafter=1}

**2021** \| **GitHub & version control in RStudio**: Mini-workshop at the Department of the Geophysical Sciences, University of Chicago  

**2019** \| **Ecology & Management of Louisiana Wildlife**: Guest Instructor, LSU  
Trained a team of students in small mammal surveying, handling, and identification  

**2018** \| **Ecology & Management of Louisiana Wildlife**: Guest Instructor, LSU  

**2017** \| **Mammalogy**: Teaching Assistant, LSU  

**2017** \| **Ecology & Management of Louisiana Wildlife**: Guest Instructor, LSU  

**2016** \| **Museum Experience for Undergraduates**: Co-founder, LSU  
"*Our mission is to train the next generation of museum researchers and advocates by exposing undergraduate students to the study of natural history, both locally and globally*."

**2015** \| **Mammalogy**: Invited Instructor, LSU  
Lead 12 undergraduate Mammalogy students on a field survey - Kisatchie National Forests, LA \

## Outreach
\everypar{\hangindent=1.23cm \hangafter=1}

**2022** \| **U Chicago Southside Science Festival**: Public science festival, demonstrations of 3D surface scanning and mesh construction  

**2021** \| **"Squirrel Expert"**: Kindergarten Class, The Philadelphia School  

**2020** \| **LSU Museum Special Saturdays**: *Bust A Move - Mammal Locomotion*. Presentation and activities on mammal locomotion for ages 5-12  

**2019** \| **LSU Night at the Museum - Mammals**: Museum specimen preparation demonstration, behind the scenes tours, and public engagement on the value of museum specimens  

**2019** \| **LSU Museum Special Saturdays**: *Life in the Mountains*  

**2017** \| **LSU Fall Fest**: Engaging with undergraduate students on the behalf of the LSU Museum of Natural Science

**2017** \| **LSU Night at the Museum - Mammals**  

**2017** \| **LSU Museum Special Saturdays**: *Risky Rodents*  

**2016** \| **LSU Fall Fest**

**2016** \| **LSU Museum 6th Grade Day**: Hosting local 6th grade students from around the Parish  

**2016** \| **Bio-Blitz - East Baton Rouge Parish**: Surveying small mammals in EBR Parish parks  

**2016** \| **LSU Fall Fest**  

**2015** \| **LSU Fall Fest**  \

## Professional Service
\everypar{\hangindent=2.85cm \hangafter=1}

\textbf{2019\enskip-\enskip present}\enskip\|\enskip Nomenclature Committee, American Society of Mammalogists  

\textbf{2019\enskip-\enskip present}\enskip\|\enskip Biodiversity Committee, American Society of Mammalogists  
*Member of Muroidea taxonomic working group*

\textbf{2022\enskip-\enskip present}\enskip\|\enskip Grants in Aid Committee, American Society of Mammalogists  

\textbf{2022\enskip-\enskip present}\enskip\|\enskip Maintenance, Phylogenetics Task View CRAN Repository  

**Journal Peer Review** \| The American Naturalist, Systematic Biology, Evolution, Ecology and Evolution, Journal of Mammalogy, Therya, Zoological Research, Journal of Mammalian Evolution, Mammalian Species, Royal Society Open Science, PeerJ, Mammalia, Biodiversity Data Journal  

**Grant Review** \| NSF CAREER Program (*Ad hoc reviewer*), American Society of Mammalogists Grants in Aid (*upcoming*)\


## Fieldwork: Museum Collection Expeditions
\begin{itemize}[noitemsep]
    \item Biota CAPTURE Project, Chicago, 2022
    \item Mt. Murud, Sarawak, Malaysia, 2019
    \item Mt. Singgalang, West Sumatra, Indonesia, 2018
    \item Mt. Talamau, West Sumatra, Indonesia, 2018
    \item Mt. Mulu, Sarawak, Malaysia, 2017
    \item Louisiana, various, 2015 - 2018
    \item Ouachita National Forest, Arkansas, 2015
    \item Denali National Park, Alaska, 2015
    \item Tongass National Forest, Juneau, Alaska, 2014  
    \item Chugach National Forest, Valdez, Alaska, 2014  
    \item Toolik Field Station, North Slope, Alaska, 2013  
    \item White Mountain Recreational Area, Alaska, various 2012 - 2015  
    \item Fairbanks Area, Alaska, various, 2011 - 2015  
\end{itemize}
